### ISSUE TITLE
Spectator: Exception: You must pass a root element to the UI.Create functions

### ISSUE THREAD

**Issue by TBestLittleHelper** [JustMe003/WarzoneMods#1]
>Sorry, the mod has failed.  Error: 
pcall failure in function Client_PresentMenuUI ret=-1 Error: Exception: You must pass a root element to the UI.Create functions

Try to open the mod menu as a spectator. Ie, this game : https://www.warzone.com/MultiPlayer?GameID=30666445
From here I think : 
https://github.com/JustMe003/WarzoneMods/blob/e2f626a4318cbaf1517deb44af2b19100d603820/Local_Deployment_Helper/Client_PresentMenuUI.lua#L17

**Comment by JustMe003** [comment]
thank you TBest. I just moved some lines around and now it runs smoothly again
